# Apache MPM event — tuned by setup.sh

<IfModule mpm_event_module>
    ServerLimit              16
    MaxRequestWorkers        400
    ThreadsPerChild          25
    MaxConnectionsPerChild   10000

    StartServers             4
    MinSpareThreads          75
    MaxSpareThreads          250
    ThreadLimit              64

    KeepAlive                On
    MaxKeepAliveRequests     500
    KeepAliveTimeout         5
</IfModule>
